"""
src.phase_a.strategies.base — Abstract interface for poisoning strategies.

Every poisoning strategy must implement this interface. The strategy
receives target queries, access to the clean corpus, and strategy-specific
configuration, and returns a list of PoisonedChunk objects ready for injection.

This design allows:
- Adding new attack strategies without modifying the injector or corpus builder.
- Configuring strategy parameters via YAML without code changes.
- Comparing different strategies in experiments by swapping configs.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

# from src.data.schema import Chunk, Query


@dataclass
class PoisonedChunk:
    """A chunk generated by a poisoning strategy, ready for injection.

    Attributes:
        chunk_id: Unique identifier (will be prefixed with 'poison_').
        text: The poisoned text content.
        strategy: Name of the strategy that generated this chunk.
        target_query_id: The query this poison targets (if applicable).
        metadata: Strategy-specific metadata (e.g., target answer, optimization steps).
    """

    chunk_id: str
    text: str
    strategy: str
    target_query_id: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


class BasePoisonStrategy(ABC):
    """Abstract base class for all poisoning strategies.

    Subclasses must implement `generate()` to produce poisoned chunks
    given a set of target queries and access to the clean corpus.
    """

    @abstractmethod
    def generate(
        self,
        target_queries: list,
        corpus_chunks: list,
        config: dict,
    ) -> list[PoisonedChunk]:
        """Generate poisoned chunks.

        Args:
            target_queries: List of Query objects to target.
            corpus_chunks: List of clean Chunk objects (for reference/context).
            config: Strategy-specific configuration parameters.

        Returns:
            A list of PoisonedChunk objects ready for injection.
        """
        ...

    @property
    @abstractmethod
    def name(self) -> str:
        """Return the strategy name (must match the config key)."""
        ...
